[book]
authors = ["DeltaChat Contributors"]
language = "en"
multilingual = false
src = "src"
title = "Webxdc"

[output.html]
default-theme = "Rust"
additional-css = ["custom.css"]
git-repository-url = "https://github.com/webxdc/webxdc_docs"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/webxdc/webxdc_docs/edit/master/{path}"
