name: Deploy Main Branch

on:
  push:
    branches:
      - main
      - new-deployment

jobs:
  upload:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: put everything in a folder so we don't accidentally upload the private key
      run: |
        mkdir webxdc.org
        mv * webxdc.org
    - name: Upload
      uses: horochx/deploy-via-scp@v1.0.1
      with:
        user: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        host: "delta.chat"
        port: 22
        local: "webxdc.org"
        remote: "/var/www/html/"

